name: memory_lowdim

obs_dim: 4
action_dim: 2

env_runner:
  _target_: diffusion_policy.env_runner.memory_env_runner.MemoryEnvRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 100
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null
  goal_masking_timestep: 20
  include_goal_flag: False

dataset:
  _target_: diffusion_policy.dataset.memory_env_dataset.MemoryLowdimDataset
  zarr_path: data/memory/env4_20gmts.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${horizon}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
  remove_goal_flag: True